[workspace]
members = [
  "elonafoobar",
  "elonafoobar-gui",
  "elonafoobar-log",
  "elonafoobar-lua",
  "elonafoobar-lua-proc-macros",
  "elonafoobar-lua-sys",
  "elonafoobar-net",
  "elonafoobar-rand",
  "elonafoobar-utils",
]
