[package]
name = "elonafoobar-rand"
version = "0.8.0"
authors = ["KI"]
edition = "2018"
publish = false

[dependencies]
rand_xoshiro = "0.6.0"

[dependencies.rand]
version = "0.8.1"
default-features = false
