[package]
name = "elonafoobar-log"
version = "0.8.0"
authors = ["KI"] # See also ../CREDITS.txt.
edition = "2018"
publish = false

[dependencies]
ansi_term = "0.12.1"
atty = "0.2.14"
log = { version = "0.4.11", features = ["std"] }
thiserror = "1.0.21"
