[package]
name = "elonafoobar-lua-proc-macros"
version = "0.8.0"
authors = ["KI"] # See also ../CREDITS.txt.
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.8"

[dependencies.syn]
version = "1.0.58"
features = ["full", "printing"]
