name: Tests

on: [push, pull_request]

jobs:
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libsmpeg-dev \
          timidity

    - name: Cache Vanilla Elona
      uses: actions/cache@v2
      with:
        path: deps/elona
        key: elona122

    - name: Download Vanilla Elona
      run: |
        if [ ! -d deps/elona ]
        then
          mkdir deps
          wget --no-verbose "http://ylvania.style.coocan.jp/file/elona122.zip"
          unzip -qq elona122.zip -d deps
        fi

    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Test
      run: |
        touch elonafoobar/src/bin/elona.rs
        cargo test --verbose


  test-macos:
    name: Test on macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: |
        brew update
        brew install -f \
          sdl2 \
          sdl2_image \
          sdl2_mixer \
          sdl2_ttf

    - name: Cache Vanilla Elona
      uses: actions/cache@v2
      with:
        path: deps/elona
        key: elona122

    - name: Download Vanilla Elona
      run: |
        if [ ! -d deps/elona ]
        then
          mkdir deps
          wget --no-verbose "http://ylvania.style.coocan.jp/file/elona122.zip"
          unzip -qq elona122.zip -d deps
        fi

    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Test
      run: |
        touch elonafoobar/src/bin/elona.rs
        cargo test --verbose


  format:
    name: Run cargo fmt
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run cargo fmt
      run: |
        cargo fmt -- --check


  lint:
    name: Run cargo clippy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run cargo clippy
      run: |
        cargo clippy -- -D warnings
